apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-container
        image: 024230653708.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080   # Updated to match Spring Boot
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080          # Route traffic from port 80 to 8080
  selector:
    app: spring-boot-app
